# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeniorProbBackUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeniorProbBackUp
	pod 'Parse'
	pod 'AlamofireImage'

  target 'SeniorProbBackUpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeniorProbBackUpUITests' do
    # Pods for testing
  end

end
